/* ============================================================
   BD — atlas content: geometry recipes, colours, functions, links
   Every builder returns RIGHT-hemisphere / midline geometry;
   mirrored copies are generated by the renderer.
   ============================================================ */
var BD = (function () {
  'use strict';
  var g = BG;

  var STRUCTURES = [

  /* ---------------- cerebral cortex ---------------- */
  { id:'frontal', name:'Frontal lobe', grp:'Cerebral cortex', color:0x4c7fe3, cortex:true,
    mirror:true, solid:true, key:1, label:[30,28,60],
    fn:'Executive control: planning, working memory, reasoning, inhibition of impulses and voluntary movement. The orbital and medial sectors weigh reward, risk and social consequence; the lateral prefrontal cortex holds and manipulates information online.',
    loc:'Anterior to the central sulcus, above the lateral (Sylvian) fissure. Broca\u2019s area sits in the inferior frontal gyrus of the dominant (usually left) hemisphere \u2014 damage there produces expressive aphasia.',
    conn:['motor','parietal','temporal','cingulate','thalamus','caudate','cc','slf','unc','thalrad'] },

  { id:'motor', name:'Primary motor cortex (M1)', grp:'Cerebral cortex', color:0xef5f4c, cortex:true,
    mirror:true, solid:true, key:1, label:[26,50,14],
    fn:'Issues the commands for voluntary movement. Its giant Betz cells start the corticospinal tract, and the body is mapped along the strip as the motor homunculus \u2014 leg near the midline, face laterally.',
    loc:'Precentral gyrus, the strip immediately in front of the central sulcus. A lesion here causes contralateral weakness (upper motor neurone pattern).',
    conn:['somato','frontal','parietal','cerebellum','thalamus','pallidum','cst','cc'] },

  { id:'somato', name:'Primary somatosensory cortex (S1)', grp:'Cerebral cortex', color:0xf5a623, cortex:true,
    mirror:true, solid:true, key:1, label:[29,49,-4],
    fn:'Receives touch, vibration, joint position and pain/temperature signals from the opposite half of the body, arranged as the sensory homunculus. It supports two-point discrimination and stereognosis.',
    loc:'Postcentral gyrus, immediately behind the central sulcus; input arrives from the ventral posterior nucleus of the thalamus.',
    conn:['motor','parietal','thalamus','cerebellum','thalrad','cc'] },

  { id:'parietal', name:'Parietal lobe', grp:'Cerebral cortex', color:0xf2d34b, cortex:true,
    mirror:true, solid:true, key:1, label:[38,37,-27],
    fn:'Builds the sense of space and of the body within it: integrating touch, vision and proprioception into reaching, grasping and directed attention. The left side supports calculation, reading and praxis.',
    loc:'Between the central sulcus and the parieto-occipital sulcus. Right-sided damage classically causes contralateral hemispatial neglect.',
    conn:['somato','occipital','temporal','frontal','cingulate','thalamus','slf','cc'] },

  { id:'temporal', name:'Temporal lobe', grp:'Cerebral cortex', color:0x35b58a, cortex:true,
    mirror:true, solid:true, key:1, label:[54,-20,6],
    fn:'Hearing, language comprehension, object and face recognition along its inferior surface, and \u2014 through the hippocampus buried in its medial wall \u2014 the laying down of new memories.',
    loc:'Below the lateral fissure. Wernicke\u2019s area (posterior superior temporal gyrus, dominant hemisphere) supports comprehension; the medial surface is the commonest origin of focal epilepsy.',
    conn:['auditory','hippocampus','amygdala','frontal','parietal','occipital','thalamus','unc','slf','ifof'] },

  { id:'auditory', name:'Primary auditory cortex (A1)', grp:'Cerebral cortex', color:0x0f8f8f, cortex:true,
    mirror:true, solid:true, key:2, label:[64,-6,0],
    fn:'Tonotopic first cortical stage of hearing \u2014 frequency is mapped systematically across the surface. It extracts pitch, timing and onset cues that downstream belt areas turn into speech and music.',
    loc:'Heschl\u2019s gyrus on the superior temporal plane, hidden inside the lateral fissure; driven by the medial geniculate nucleus of the thalamus.',
    conn:['temporal','thalamus','cc','slf'] },

  { id:'occipital', name:'Occipital lobe', grp:'Cerebral cortex', color:0xb65fa8, cortex:true,
    mirror:true, solid:true, key:1, label:[28,10,-68],
    fn:'Visual cortex. Beyond V1 the extrastriate areas separate motion, colour, form and depth, feeding the dorsal \u201cwhere/how\u201d stream to the parietal lobe and the ventral \u201cwhat\u201d stream to the temporal lobe.',
    loc:'Posterior pole, behind the parieto-occipital sulcus; supplied mainly by the posterior cerebral artery.',
    conn:['v1','parietal','temporal','thalamus','optrad','ifof','cc'] },

  { id:'v1', name:'Primary visual cortex (V1)', grp:'Cerebral cortex', color:0x7a3e9d, cortex:true,
    mirror:true, solid:true, key:2, label:[14,6,-80],
    fn:'The striate cortex: first cortical map of the visual field, retinotopic and organised into orientation columns and ocular-dominance stripes. Each hemisphere represents the opposite visual half-field.',
    loc:'Banks of the calcarine sulcus on the medial occipital surface. Bilateral damage causes cortical blindness; unilateral damage a contralateral homonymous hemianopia.',
    conn:['occipital','thalamus','optrad','cc'] },

  { id:'cingulate', name:'Cingulate cortex', grp:'Limbic system', color:0xe38bb8, cortex:true,
    mirror:true, solid:true, key:1, label:[3,21,4],
    fn:'Limbic hub for error monitoring, conflict and effort, pain affect, autonomic control and motivation. The anterior part tags events with emotional salience; the posterior part belongs to the default-mode network.',
    loc:'Arches over the corpus callosum on the medial surface, wrapped by the cingulum bundle.',
    conn:['frontal','parietal','hippocampus','amygdala','thalamus','cc','cing_b','accumbens'] },

  { id:'insula', name:'Insular cortex', grp:'Limbic system', color:0x8e6bd1, mirror:true, solid:true,
    key:2, label:[37,-3,12],
    fn:'Interoceptive cortex: taste, visceral sensation, heartbeat and breath awareness, temperature and pain unpleasantness, disgust and craving. Also part of the salience network that switches attention.',
    loc:'Buried in the depth of the lateral fissure, covered by the frontal, parietal and temporal opercula.',
    conn:['temporal','frontal','cingulate','amygdala','thalamus','putamen'],
    geom:function(){ return g.blob([6,14,18],{rot:[0,0.12,0.12],pos:[35,-2,10],seg:32,ring:22}); } },

  /* ---------------- limbic ---------------- */
  { id:'hippocampus', name:'Hippocampus', grp:'Limbic system', color:0xe8c547, mirror:true, solid:true,
    key:1, label:[30,-14,-6],
    fn:'Converts experience into long-term declarative memory and builds cognitive maps of space (place cells). Output leaves through the fornix; new memories are consolidated to cortex over months.',
    loc:'Curled along the floor of the temporal horn of the lateral ventricle. Bilateral loss causes dense anterograde amnesia; it is highly vulnerable to hypoxia and to Alzheimer pathology.',
    conn:['temporal','cingulate','amygdala','fornix','thalamus','hypothalamus','cing_b'],
    geom:function(){ return g.tube([[25,-13,7],[26,-11,-3],[27,-9,-12],[25,-6,-20],[20,-2,-25]],
                                  [6,5.6,5,4.4,3.4],{rad:16}); } },

  { id:'amygdala', name:'Amygdala', grp:'Limbic system', color:0xd64545, mirror:true, solid:true,
    key:1, label:[26,-18,16],
    fn:'Assigns emotional value \u2014 especially threat \u2014 to sensory input, drives fear learning and the autonomic/endocrine stress response, and stamps emotional events into memory.',
    loc:'Immediately anterior and superior to the hippocampal head, in the medial temporal lobe; projects to the hypothalamus and brainstem via the stria terminalis.',
    conn:['hippocampus','temporal','cingulate','hypothalamus','thalamus','insula','accumbens','unc'],
    geom:function(){ return g.blob([7.4,6.6,7.6],{pos:[24,-13,12],seg:28,ring:20}); } },

  { id:'fornix', name:'Fornix', grp:'Limbic system', color:0xdcd3be, mirror:true, solid:false,
    key:2, label:[8,18,-14],
    fn:'The hippocampus\u2019 main output cable. Fibres arch from the hippocampal fimbria over the thalamus to the mammillary bodies and anterior thalamus, closing the Papez memory circuit.',
    loc:'Forms the crus, body and columns beneath the corpus callosum. Section of the fornix impairs the formation of new episodic memories.',
    conn:['hippocampus','hypothalamus','thalamus','cingulate','cc'],
    geom:function(){ return g.tube([[24,-9,-22],[17,-1,-27],[10,9,-20],[6,15,-6],[5,14,6],[5,8,12],[4,-2,11]],
                                  [2.6,2.4,2.2,2.2,2.2,2,1.8],{rad:10}); } },

  /* ---------------- basal ganglia ---------------- */
  { id:'caudate', name:'Caudate nucleus', grp:'Basal ganglia', color:0xe86a2c, mirror:true, solid:true,
    key:1, label:[16,16,24],
    fn:'With the putamen it forms the striatum, the input stage of the basal ganglia. It gates habit learning, goal-directed action selection and reward-based feedback loops with prefrontal cortex.',
    loc:'C-shaped, following the lateral ventricle: head bulging into the frontal horn, body along the thalamus, tail curving into the temporal horn. Atrophies early in Huntington disease.',
    conn:['frontal','putamen','pallidum','thalamus','nigra','ic','cingulate'],
    geom:function(){ return g.tube([[13,3,22],[14,9,14],[16,14,2],[17,12,-12],[19,7,-22],[22,-3,-24],[25,-8,-14],[26,-10,-4]],
                                  [6.6,6,4.6,3.6,3,2.6,2.3,2],{rad:14}); } },

  { id:'putamen', name:'Putamen', grp:'Basal ganglia', color:0xd65a7e, mirror:true, solid:true,
    key:1, label:[34,4,10],
    fn:'Large striatal nucleus for motor habit and skill learning: it scales movement amplitude and speed and helps chain over-learned action sequences.',
    loc:'Lateral to the globus pallidus and internal capsule, deep to the insula. Together they form the lentiform nucleus.',
    conn:['motor','frontal','pallidum','caudate','nigra','thalamus','insula','ic'],
    geom:function(){ return g.blob([7,12.5,17],{rot:[0,0.1,0.1],pos:[26,0,4],seg:30,ring:22}); } },

  { id:'pallidum', name:'Globus pallidus', grp:'Basal ganglia', color:0x9b8be0, mirror:true, solid:true,
    key:2, label:[19,-4,2],
    fn:'Output stage of the basal ganglia. Its internal segment tonically inhibits the motor thalamus; releasing that brake permits movement, and it is a standard deep-brain-stimulation target in dystonia and Parkinson disease.',
    loc:'Medial to the putamen, lateral to the internal capsule; divided into internal and external segments by a thin medullary lamina.',
    conn:['putamen','caudate','thalamus','nigra','motor','ic'],
    geom:function(){ return g.blob([4.6,9,11],{rot:[0,0.08,0.1],pos:[18.5,-1,2],seg:26,ring:18}); } },

  { id:'accumbens', name:'Nucleus accumbens', grp:'Basal ganglia', color:0xf5b7c6, mirror:true, solid:true,
    key:2, label:[12,-11,26],
    fn:'Ventral striatum \u2014 the reward and motivation interface. Dopamine arriving from the ventral tegmental area signals reward prediction error; central to addiction, anhedonia and incentive salience.',
    loc:'Where the caudate head meets the putamen below the anterior limb of the internal capsule.',
    conn:['frontal','cingulate','amygdala','hippocampus','nigra','hypothalamus','pallidum'],
    geom:function(){ return g.blob([5.2,4.6,5.4],{pos:[11,-7,21],seg:22,ring:16}); } },

  { id:'nigra', name:'Substantia nigra', grp:'Basal ganglia', color:0x3c3c52, mirror:true, solid:true,
    key:2, label:[10,-20,-2],
    fn:'Dark, melanin-rich dopaminergic nucleus. Its pars compacta supplies the striatum with dopamine; loss of \u224860\u201380% of these neurones produces the bradykinesia, rigidity and tremor of Parkinson disease.',
    loc:'A plate in the ventral midbrain between the cerebral peduncle and the red nucleus.',
    conn:['caudate','putamen','pallidum','midbrain','thalamus','accumbens'],
    geom:function(){ return g.blob([6,2.4,4.4],{rot:[0.1,0.2,0],pos:[8,-15,-1],seg:22,ring:14}); } },

  /* ---------------- diencephalon ---------------- */
  { id:'thalamus', name:'Thalamus', grp:'Diencephalon', color:0x2fa8c9, mirror:true, solid:true,
    key:1, label:[14,10,-8],
    fn:'The relay and gate of the forebrain: almost every sensory, motor and limbic pathway to cortex is routed and filtered here, and its reticular shell sets attention, arousal and sleep spindles.',
    loc:'Paired egg-shaped mass on either side of the third ventricle. Specific relays: LGN\u2192vision, MGN\u2192hearing, VPL/VPM\u2192body sensation, VA/VL\u2192motor.',
    conn:['frontal','motor','somato','parietal','temporal','occipital','v1','auditory','cingulate','pallidum','cerebellum','hypothalamus','thalrad','ic','optrad'],
    geom:function(){ return g.blob([9.5,10,17],{rot:[0,0.3,0],pos:[11,5,-4],seg:32,ring:22}); } },

  { id:'hypothalamus', name:'Hypothalamus', grp:'Diencephalon', color:0xf2c744, mirror:true, solid:true,
    key:1, label:[8,-14,12],
    fn:'Master homeostatic controller: temperature, thirst, hunger, circadian timing (suprachiasmatic nucleus), stress and sex hormones, autonomic balance and defensive behaviour \u2014 largely by commanding the pituitary.',
    loc:'Below the thalamus, forming the floor and lower walls of the third ventricle; continuous with the pituitary stalk and mammillary bodies.',
    conn:['amygdala','hippocampus','fornix','pituitary','midbrain','thalamus','cingulate','accumbens'],
    geom:function(){ return g.blob([6,5,7.6],{pos:[4.5,-9,7],seg:24,ring:18}); } },

  { id:'pituitary', name:'Pituitary gland', grp:'Ventricles & glands', color:0xf09cc0, mirror:false, solid:true,
    key:2, label:[0,-27,16],
    fn:'Endocrine master gland. The anterior lobe releases growth hormone, TSH, ACTH, prolactin, LH and FSH under hypothalamic control; the posterior lobe stores oxytocin and vasopressin made in the hypothalamus.',
    loc:'Sits in the sella turcica, joined to the hypothalamus by the infundibulum, just behind the optic chiasm \u2014 hence the bitemporal field loss of an expanding adenoma.',
    conn:['hypothalamus','optic'],
    geom:function(){ return g.mergeGeoms([ g.blob([5.2,4.2,5.2],{pos:[0,-20,13],seg:22,ring:16}),
                                          g.tube([[0,-13,9],[0,-16,11],[0,-19,12]],[1.8,1.6,1.6],{rad:10}) ]); } },

  { id:'pineal', name:'Pineal gland', grp:'Ventricles & glands', color:0xc9a0dc, mirror:false, solid:true,
    key:3, label:[0,10,-32],
    fn:'Secretes melatonin on a light-entrained schedule relayed from the suprachiasmatic nucleus, setting sleep\u2013wake timing and seasonal rhythm. Calcifies with age, making it a useful midline landmark on imaging.',
    loc:'Projects backwards from the posterior wall of the third ventricle above the midbrain tectum.',
    conn:['third_vent','hypothalamus','midbrain'],
    geom:function(){ return g.blob([3.6,3,4.4],{pos:[0,5,-26],seg:20,ring:14}); } },

  /* ---------------- brainstem & cerebellum ---------------- */
  { id:'midbrain', name:'Midbrain (mesencephalon)', grp:'Brainstem & cerebellum', color:0xc0705a,
    mirror:false, solid:true, key:1, label:[0,-8,18],
    fn:'Carries all traffic between cortex and lower brainstem, and houses reflex centres: superior colliculi for visual orienting and saccades, inferior colliculi for auditory reflexes, plus the oculomotor nuclei and red nucleus.',
    loc:'Between the thalamus above and the pons below; pierced by the cerebral aqueduct. Obstruction there causes obstructive hydrocephalus.',
    conn:['thalamus','pons','cerebellum','nigra','cst','hypothalamus','optic'],
    geom:function(){ return g.tube([[0,-5,-2],[0,-13,0],[0,-19,1]],[10,11,10.5],{rad:20,squash:0.86}); } },

  { id:'pons', name:'Pons', grp:'Brainstem & cerebellum', color:0xa8563f, mirror:false, solid:true,
    key:1, label:[0,-30,24],
    fn:'Bridge between cortex and cerebellum and the relay for facial sensation and movement, hearing and balance (cranial nerves V\u2013VIII). Its tegmentum holds the pontine centres for REM sleep, breathing rhythm and horizontal gaze.',
    loc:'Bulges anteriorly below the midbrain; the middle cerebellar peduncles leave its lateral surface for the cerebellum.',
    conn:['midbrain','medulla','cerebellum','mcp','cst','thalamus'],
    geom:function(){ return g.tube([[0,-19,1],[0,-27,5],[0,-35,4]],[11,14,12],{rad:20,squash:0.9}); } },

  { id:'medulla', name:'Medulla oblongata', grp:'Brainstem & cerebellum', color:0x8c4530, mirror:false,
    solid:true, key:1, label:[0,-52,16],
    fn:'Vital autonomic centre: respiratory rhythm, blood pressure and heart rate, vomiting, coughing and swallowing. The corticospinal tracts cross the midline in its pyramids, and the dorsal column nuclei relay fine touch.',
    loc:'Lowest brainstem segment, continuous with the spinal cord at the foramen magnum; cranial nerves IX\u2013XII arise here.',
    conn:['pons','cerebellum','cst','thalamus'],
    geom:function(){ return g.tube([[0,-35,3],[0,-45,1],[0,-58,-1]],[9,7.6,6],{rad:18,squash:0.92}); } },

  { id:'cerebellum', name:'Cerebellum', grp:'Brainstem & cerebellum', color:0x6fbf4a, mirror:false,
    solid:true, key:1, label:[52,-40,-56],
    fn:'Feed-forward controller of movement: it compares intended with actual motion and corrects timing, coordination, balance and eye movements, and it learns motor and cognitive routines. Holds more neurones than the rest of the brain combined.',
    loc:'Under the occipital lobes in the posterior fossa, tethered to the brainstem by three peduncles. Damage gives ipsilateral ataxia, dysmetria, intention tremor and scanning speech.',
    conn:['pons','midbrain','medulla','thalamus','motor','somato','mcp','fourth_vent'],
    geom:function(){
      return g.blob([46,22,29],{seg:110,ring:72,pos:[0,-47,-42],warp:function(X,Y,Z,ux,uy,uz){
        if (uy > 0) Y *= 0.74;                                   /* tentorial surface */
        var notch = Math.exp(-Math.pow(X/16,2)) * Math.max(0,uz);
        Z *= 1 - 0.42*notch;                                     /* space for brainstem */
        var L = Math.sqrt(X*X+Y*Y+Z*Z) || 1;
        var d = 1.25*Math.sin(Y*1.55 + Z*0.16) + 0.55*Math.sin(Y*3.2 + 1.2);
        d += 1.5*Math.exp(-Math.pow(X/7,2));                     /* vermis ridge */
        d -= 0.9*Math.exp(-Math.pow((Math.abs(X)-13)/6,2));      /* paravermian groove */
        return [X + X/L*d, Y + Y/L*d, Z + Z/L*d];
      }});
    } },

  /* ---------------- ventricles ---------------- */
  { id:'lat_vent', name:'Lateral ventricle', grp:'Ventricles & glands', color:0x6fc9f2, mirror:true,
    solid:false, opacity:0.42, key:1, label:[20,26,-4],
    fn:'Paired CSF cavity. Choroid plexus in its floor secretes cerebrospinal fluid, which flows through the foramina of Monro into the third ventricle, cushioning the brain and clearing metabolites.',
    loc:'C-shaped: frontal horn, body, atrium, occipital horn and temporal horn \u2014 wrapping around the thalamus and following the caudate and hippocampus.',
    conn:['third_vent','caudate','hippocampus','cc','thalamus'],
    geom:function(){ return g.mergeGeoms([
        g.tube([[10,12,30],[14,20,8],[17,15,-14],[20,10,-26],[17,6,-40]],[5,6.5,6,6,3.6],{rad:14}),
        g.tube([[20,10,-25],[25,-2,-21],[27,-8,-8],[26,-10,0]],[5,4.6,4.2,3.4],{rad:12}) ]); } },

  { id:'third_vent', name:'Third ventricle', grp:'Ventricles & glands', color:0x5fb8e8, mirror:false,
    solid:false, opacity:0.45, key:2, label:[0,20,4],
    fn:'Thin midline CSF slit between the two thalami. Its walls contain circumventricular organs that sample blood osmolality and hormones; CSF leaves through the cerebral aqueduct.',
    loc:'Bounded laterally by thalamus and hypothalamus, roofed by choroid plexus, with the pineal behind and optic chiasm in front.',
    conn:['lat_vent','fourth_vent','thalamus','hypothalamus','pineal'],
    geom:function(){ return g.blob([1.9,12,16],{pos:[0,3,1],seg:20,ring:16}); } },

  { id:'fourth_vent', name:'Fourth ventricle', grp:'Ventricles & glands', color:0x4fa8de, mirror:false,
    solid:false, opacity:0.45, key:3, label:[0,-26,-24],
    fn:'Diamond-shaped CSF space between brainstem and cerebellum. CSF escapes through the median and lateral apertures into the subarachnoid space; its floor carries several cranial nerve nuclei.',
    loc:'Between the pons/medulla in front and the cerebellum behind; continuous above with the cerebral aqueduct.',
    conn:['third_vent','pons','medulla','cerebellum'],
    geom:function(){ return g.blob([7.5,3.2,6],{rot:[0.2,0,0],pos:[0,-29,-14],seg:20,ring:16}); } },

  /* ---------------- commissures & deep white matter ---------------- */
  { id:'cc', name:'Corpus callosum', grp:'White matter', color:0xede6d6, mirror:false, solid:true,
    key:1, label:[0,34,44],
    fn:'The largest white-matter bundle in the brain: roughly 200 million axons that keep the two hemispheres in register, sharing sensory, motor and language information between matching cortical areas.',
    loc:'Rostrum, genu, body and splenium, arching over the lateral ventricles. Surgical section (for epilepsy) produces the split-brain syndrome.',
    conn:['frontal','motor','somato','parietal','temporal','occipital','cingulate','callrad','lat_vent'],
    geom:function(){ return g.ccGeom(); } },

  { id:'ac', name:'Anterior commissure', grp:'White matter', color:0xd8cfb8, mirror:false, solid:true,
    key:3, label:[0,4,26],
    fn:'Compact bundle crossing the midline in front of the third ventricle, linking the two temporal lobes, amygdalae and olfactory regions \u2014 an emotional and olfactory counterpart to the corpus callosum.',
    loc:'Standard stereotactic landmark: the AC\u2013PC line defines the reference plane for neurosurgical and imaging coordinates.',
    conn:['amygdala','temporal','olfactory','hypothalamus'],
    geom:function(){ return g.tube([[-15,-2,17],[-8,-1,19],[0,-1,19.5],[8,-1,19],[15,-2,17]],
                                   [1.8,2.2,2.4,2.2,1.8],{rad:12}); } },

  { id:'ic', name:'Internal capsule', grp:'White matter', color:0xe4dcc6, mirror:true, solid:true,
    key:2, label:[22,4,14],
    fn:'The funnel through which almost all cortical traffic to and from the brainstem and spinal cord passes \u2014 corticospinal, corticobulbar and thalamocortical fibres packed into a few millimetres.',
    loc:'V-shaped in axial section between caudate/thalamus medially and the lentiform nucleus laterally. A small lacunar stroke in the posterior limb can cause a dense contralateral hemiplegia.',
    conn:['motor','frontal','somato','thalamus','pallidum','putamen','caudate','cst','thalrad'],
    geom:function(){ return g.tube([[15,8,17],[17,4,8],[19,0,-2],[20,-4,-11]],[5,5.6,5,4],{rad:16,squash:0.34}); } },

  /* ---------------- cranial sensory pathways ---------------- */
  { id:'optic', name:'Optic nerve, chiasm & tract', grp:'Cranial pathways', color:0xf2ea8a, mirror:false,
    solid:true, key:1, label:[0,-20,46],
    fn:'Carries vision from retina to brain. At the chiasm the nasal half of each retina crosses, so each optic tract then carries the complete opposite visual half-field to the lateral geniculate nucleus.',
    loc:'Runs beneath the frontal lobes; the chiasm lies directly above the pituitary. Chiasmal compression produces bitemporal hemianopia, a tract lesion a homonymous hemianopia.',
    conn:['v1','thalamus','optrad','midbrain','hypothalamus','pituitary'],
    geom:function(){
      var parts = [ g.blob([9,3.2,5],{pos:[0,-14,27],seg:24,ring:16}) ];
      [1,-1].forEach(function(s){
        parts.push(g.tube([[s*7,-15,45],[s*5,-14,36],[s*2,-14,29]],[2.6,2.6,3],{rad:12}));
        parts.push(g.tube([[s*4,-14,25],[s*10,-13,18],[s*14,-12,6]],[3,2.8,2.6],{rad:12}));
      });
      return g.mergeGeoms(parts); } },

  { id:'olfactory', name:'Olfactory bulb & tract', grp:'Cranial pathways', color:0xb7d96b, mirror:true,
    solid:true, key:2, label:[8,-30,48],
    fn:'Smell enters here directly \u2014 the only sensory system that reaches cortex without a thalamic relay, which is why odours have such immediate access to memory and emotion.',
    loc:'Lies on the cribriform plate under the orbital frontal cortex; the tract runs back to piriform cortex, amygdala and entorhinal cortex. Early loss of smell is a warning sign in Parkinson and Alzheimer disease.',
    conn:['amygdala','temporal','frontal','ac','hippocampus'],
    geom:function(){ return g.mergeGeoms([
        g.blob([3.2,2.6,6.5],{pos:[6,-23,45],seg:20,ring:14}),
        g.tube([[6,-23,41],[7,-22,32],[9,-21,22]],[1.8,1.7,1.6],{rad:10}) ]); } }
  ];

  /* ---------------- white-matter tracts (connections) ---------------- */
  var TRACTS = [
  { id:'cst', name:'Corticospinal tract', color:0xff7a4d, key:1, label:[14,-4,-6],
    fn:'The pyramidal motor highway: axons from motor cortex descend through the internal capsule, midbrain and pons, cross in the medullary pyramids and drive spinal motor neurones for skilled voluntary movement.',
    loc:'Lesions above the decussation weaken the opposite side of the body, with spasticity, hyper-reflexia and an upgoing plantar response.',
    conn:['motor','somato','ic','midbrain','pons','medulla'],
    geom:function(){ return g.tube([[24,44,2],[20,28,0],[16,12,0],[12,-2,-1],[8,-14,0],[6,-27,6],[3,-45,2],[1,-58,0]],
                                   [3.4,3.2,3,2.8,2.6,2.6,2.4,2.2],{rad:12}); } },

  { id:'slf', name:'Superior longitudinal / arcuate fasciculus', color:0x59c2ff, key:1, label:[46,30,-2],
    fn:'Long dorsal association bundle arching from frontal to parietal and temporal cortex. Its arcuate portion links Broca\u2019s and Wernicke\u2019s areas; damage produces conduction aphasia, with intact comprehension but failed repetition.',
    loc:'Runs above the insula in the white matter of the supratemporal plane.',
    conn:['frontal','parietal','temporal','auditory','motor'],
    geom:function(){ return g.tube([[34,22,30],[42,30,12],[44,26,-10],[42,10,-22],[40,-6,-12],[38,-12,2]],
                                   [2.8,2.8,2.8,2.6,2.6,2.4],{rad:12}); } },

  { id:'unc', name:'Uncinate fasciculus', color:0xffd166, key:2, label:[30,-18,30],
    fn:'Hook-shaped bundle joining orbitofrontal cortex to the temporal pole and amygdala \u2014 a route for emotional valuation, social judgement and proper-name retrieval; it matures slowly into the third decade.',
    loc:'Curves around the limen insulae in the depth of the lateral fissure.',
    conn:['frontal','temporal','amygdala','insula'],
    geom:function(){ return g.tube([[20,-14,38],[27,-14,28],[31,-15,20],[32,-13,14],[30,-10,10]],
                                   [2.4,2.4,2.3,2.2,2.2],{rad:12}); } },

  { id:'cing_b', name:'Cingulum bundle', color:0xb388ff, key:2, label:[10,32,-12],
    fn:'Follows the cingulate gyrus around the corpus callosum and down into the parahippocampal region, tying together the limbic circuit for emotion, memory retrieval and the default-mode network.',
    loc:'Just above the corpus callosum on the medial surface, continuing into the temporal lobe.',
    conn:['cingulate','hippocampus','frontal','parietal','amygdala'],
    geom:function(){ return g.tube([[7,16,34],[8,28,22],[9,32,2],[9,26,-20],[11,14,-30],[16,-2,-26],[20,-8,-14]],
                                   [2.3,2.3,2.3,2.2,2.2,2.1,2],{rad:12}); } },

  { id:'ifof', name:'Inferior fronto-occipital fasciculus', color:0x4dd6b0, key:2, label:[34,-2,-30],
    fn:'Ventral stream cable running the whole length of the hemisphere, linking occipital and posterior temporal visual areas to the frontal lobe \u2014 the route for reading, semantic access and object naming.',
    loc:'Passes below the insula through the external capsule and temporal stem.',
    conn:['occipital','temporal','frontal','v1'],
    geom:function(){ return g.tube([[26,-4,42],[32,-2,24],[34,0,0],[32,0,-24],[28,-2,-42]],
                                   [2.5,2.5,2.5,2.4,2.3],{rad:12}); } },

  { id:'optrad', name:'Optic radiation', color:0xede97a, key:2, label:[24,2,-30],
    fn:'Geniculocalcarine fibres from the lateral geniculate nucleus to V1. The lower loop (Meyer\u2019s loop) swings forward into the temporal lobe, so temporal surgery can clip the upper visual quadrant.',
    loc:'Sweeps around the atrium of the lateral ventricle to the calcarine cortex.',
    conn:['thalamus','v1','occipital','optic'],
    geom:function(){ return g.tube([[14,-11,4],[20,-6,-8],[24,0,-24],[18,4,-40],[10,6,-48]],
                                   [2.4,2.3,2.3,2.2,2],{rad:12}); } },

  { id:'thalrad', name:'Thalamocortical radiations', color:0x7fe0d0, key:2, label:[26,24,8],
    fn:'Fanning projections that carry every thalamic relay up to its cortical target and the reciprocal corticothalamic feedback \u2014 the anatomical substrate of thalamocortical rhythms in sleep and attention.',
    loc:'Radiate from the thalamus through the internal capsule into the corona radiata.',
    conn:['thalamus','frontal','parietal','motor','somato','ic','temporal'],
    geom:function(){ return g.mergeGeoms([
        g.tube([[13,7,4],[18,20,18],[26,34,30]],[2.2,2,1.8],{rad:10}),
        g.tube([[13,8,-2],[20,26,-6],[30,42,-14]],[2.2,2,1.8],{rad:10}),
        g.tube([[13,4,-8],[22,6,-26],[30,4,-44]],[2.2,2,1.8],{rad:10}),
        g.tube([[13,2,2],[22,-6,10],[32,-14,16]],[2.2,2,1.8],{rad:10}) ]); } },

  { id:'callrad', name:'Callosal radiations', color:0xefe6d0, key:3, label:[26,48,30],
    fn:'The fibres of the corpus callosum fanning out into each hemisphere \u2014 forceps minor to the frontal poles, forceps major to the occipital poles, and the tapetum sweeping around the ventricles.',
    loc:'Spread from the callosal body through the centrum semiovale to the cortex.',
    conn:['cc','frontal','parietal','occipital','temporal','motor'],
    geom:function(){ return g.mergeGeoms([
        g.tube([[6,24,32],[16,36,36],[26,44,34]],[2,1.8,1.6],{rad:10}),
        g.tube([[6,28,10],[18,42,8],[30,50,4]],[2,1.8,1.6],{rad:10}),
        g.tube([[6,26,-14],[20,38,-18],[32,40,-24]],[2,1.8,1.6],{rad:10}),
        g.tube([[6,14,-36],[16,12,-46],[26,10,-56]],[2,1.8,1.6],{rad:10}),
        g.tube([[6,6,34],[14,-2,42],[22,-10,46]],[2,1.8,1.6],{rad:10}) ]); } },

  { id:'mcp', name:'Middle cerebellar peduncle', color:0xa0e06b, key:2, label:[26,-34,-14],
    fn:'The massive input cable to the cerebellum: cortical intentions are relayed through the pontine nuclei and cross into the opposite cerebellar hemisphere, so the cerebellum can compare plan with execution.',
    loc:'Leaves the lateral pons and enters the cerebellar white matter alongside the superior and inferior peduncles.',
    conn:['pons','cerebellum','motor','thalamus'],
    geom:function(){ return g.tube([[8,-28,6],[16,-30,-4],[23,-34,-16]],[4.2,4,3.6],{rad:14}); } }
  ];

  TRACTS.forEach(function (t) { t.grp = 'White-matter tracts'; t.mirror = true; t.solid = false; t.tract = true; });

  var GROUPS = ['Cerebral cortex', 'Limbic system', 'Basal ganglia', 'Diencephalon',
                'Brainstem & cerebellum', 'White matter', 'White-matter tracts',
                'Ventricles & glands', 'Cranial pathways'];

  return { STRUCTURES: STRUCTURES, TRACTS: TRACTS, GROUPS: GROUPS,
           ALL: STRUCTURES.concat(TRACTS) };
})();
